[[AMGX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "49a9b2455017b89ca83e19da8bee7cec48a4b961"
libc = "glibc"
os = "linux"

    [[AMGX.download]]
    sha256 = "658b02d13debb8f5c6751143707bf38e6616a390bc1d61f48cea3fcaec873502"
    url = "https://github.com/JuliaBinaryWrappers/AMGX_jll.jl/releases/download/AMGX-v2.1.0+0/AMGX.v2.1.0.x86_64-linux-gnu-cxx11.tar.gz"
